setlocal

@rem enter this directory
cd /d %~dp0

set TOOLS_PATH=..\ProtoTools

if not exist "./AutoGenerated" mkdir AutoGenerated

%TOOLS_PATH%\protoc.exe Protos/CMM_Parallel_Runner.proto -I ./Protos --csharp_out ./AutoGenerated --grpc_out ./AutoGenerated --plugin=protoc-gen-grpc=%TOOLS_PATH%\grpc_csharp_plugin.exe
%TOOLS_PATH%\protoc.exe Protos/CMM_Parallel_Runner.proto -I ./Protos  --csharp_out ./AutoGenerated

endlocal